SKILLTABS = {
    0: 'Bow skills (Ama)',
    1: 'PM skills (Ama)',
    2: 'Java skills (Ama)',
    8: 'Fire skills (Sorc)',
    9: 'Light skills (Sorc)',
    10: 'Cold skills (Sorc)',
    16: 'Curse skills (Nec)',
    17: 'PB skills (Nec)',
    18: 'Summon skills (Nec)',
    24: 'Combat skills (Pala)',
    25: 'Offensive skills (Pala)',
    26: 'Defensive skills (Pala)',
    32: 'Combat skills (Barb)',
    33: 'Mastery skills (Barb)',
    34: 'Warcry skills (Barb)',
    40: 'Summon skills (Druid)',
    41: 'Shapeshifting skills (Druid)',
    42: 'Ele skills (Druid)',
    48: 'Trap skills (Assa)',
    49: 'Shadow skills (Assa)',
    50: 'Martial skills (Assa'
}

SKILLS = {
    0: 'Attack',
    1: 'Kick',
    2: 'Throw',
    3: 'Unsummon',
    4: 'Left Hand Throw',
    5: 'Left Hand Swing',
    6: 'Magic Arrow',
    7: 'Fire Arrow',
    8: 'Inner Sight',
    9: 'Critical Strike',
    10: 'Jab',
    11: 'Cold Arrow',
    12: 'Multiple Shot',
    13: 'Dodge',
    14: 'Power Strike',
    15: 'Poison Javelin',
    16: 'Exploding Arrow',
    17: 'Slow Missiles',
    18: 'Avoid',
    19: 'Impale',
    20: 'Lightning Bolt',
    21: 'Ice Arrow',
    22: 'Guided Arrow',
    23: 'Penetrate',
    24: 'Charged Strike',
    25: 'Plague Javelin',
    26: 'Strafe',
    27: 'Immolation Arrow',
    28: 'Dopplezon',
    29: 'Evade',
    30: 'Fend',
    31: 'Freezing Arrow',
    32: 'Valkyrie',
    33: 'Pierce',
    34: 'Lightning Strike',
    35: 'Lightning Fury',
    36: 'Fire Bolt',
    37: 'Warmth',
    38: 'Charged Bolt',
    39: 'Ice Bolt',
    40: 'Frozen Armor',
    41: 'Inferno',
    42: 'Static Field',
    43: 'Telekinesis',
    44: 'Frost Nova',
    45: 'Ice Blast',
    46: 'Blaze',
    47: 'Fire Ball',
    48: 'Nova',
    49: 'Lightning',
    50: 'Shiver Armor',
    51: 'Fire Wall',
    52: 'Enchant',
    53: 'Chain Lightning',
    54: 'Teleport',
    55: 'Glacial Spike',
    56: 'Meteor',
    57: 'Thunder Storm',
    58: 'Energy Shield',
    59: 'Blizzard',
    60: 'Chilling Armor',
    61: 'Fire Mastery',
    62: 'Hydra',
    63: 'Lightning Mastery',
    64: 'Frozen Orb',
    65: 'Cold Mastery',
    66: 'Amplify Damage',
    67: 'Teeth',
    68: 'Bone Armor',
    69: 'Skeleton Mastery',
    70: 'Raise Skeleton',
    71: 'Dim Vision',
    72: 'Weaken',
    73: 'Poison Dagger',
    74: 'Corpse Explosion',
    75: 'Clay Golem',
    76: 'Iron Maiden',
    77: 'Terror',
    78: 'Bone Wall',
    79: 'Golem Mastery',
    80: 'Raise Skeletal Mage',
    81: 'Confuse',
    82: 'Life Tap',
    83: 'Poison Explosion',
    84: 'Bone Spear',
    85: 'BloodGolem',
    86: 'Attract',
    87: 'Decrepify',
    88: 'Bone Prison',
    89: 'Summon Resist',
    90: 'IronGolem',
    91: 'Lower Resist',
    92: 'Poison Nova',
    93: 'Bone Spirit',
    94: 'FireGolem',
    95: 'Revive',
    96: 'Sacrifice',
    97: 'Smite',
    98: 'Might',
    99: 'Prayer',
    100: 'Resist Fire',
    101: 'Holy Bolt',
    102: 'Holy Fire',
    103: 'Thorns',
    104: 'Defiance',
    105: 'Resist Cold',
    106: 'Zeal',
    107: 'Charge',
    108: 'Blessed Aim',
    109: 'Cleansing',
    110: 'Resist Lightning',
    111: 'Vengeance',
    112: 'Blessed Hammer',
    113: 'Concentration',
    114: 'Holy Freeze',
    115: 'Vigor',
    116: 'Conversion',
    117: 'Holy Shield',
    118: 'Holy Shock',
    119: 'Sanctuary',
    120: 'Meditation',
    121: 'Fist of the Heavens',
    122: 'Fanaticism',
    123: 'Conviction',
    124: 'Redemption',
    125: 'Salvation',
    126: 'Bash',
    127: 'Sword Mastery',
    128: 'Axe Mastery',
    129: 'Mace Mastery',
    130: 'Howl',
    131: 'Find Potion',
    132: 'Leap',
    133: 'Double Swing',
    134: 'Pole Arm Mastery',
    135: 'Throwing Mastery',
    136: 'Spear Mastery',
    137: 'Taunt',
    138: 'Shout',
    139: 'Stun',
    140: 'Double Throw',
    141: 'Increased Stamina',
    142: 'Find Item',
    143: 'Leap Attack',
    144: 'Concentrate',
    145: 'Iron Skin',
    146: 'Battle Cry',
    147: 'Frenzy',
    148: 'Increased Speed',
    149: 'Battle Orders',
    150: 'Grim Ward',
    151: 'Whirlwind',
    152: 'Berserk',
    153: 'Natural Resistance',
    154: 'War Cry',
    155: 'Battle Command',
    156: 'Fire Hit',
    157: 'UnHolyBolt',
    158: 'SkeletonRaise',
    159: 'MaggotEgg',
    160: 'ShamanFire',
    161: 'MagottUp',
    162: 'MagottDown',
    163: 'MagottLay',
    164: 'AndrialSpray',
    165: 'Jump',
    166: 'Swarm Move',
    167: 'Nest',
    168: 'Quick Strike',
    169: 'VampireFireball',
    170: 'VampireFirewall',
    171: 'VampireMeteor',
    172: 'GargoyleTrap',
    173: 'SpiderLay',
    174: 'VampireHeal',
    175: 'VampireRaise',
    176: 'Submerge',
    177: 'FetishAura',
    178: 'FetishInferno',
    179: 'ZakarumHeal',
    180: 'Emerge',
    181: 'Resurrect',
    182: 'Bestow',
    183: 'MissileSkill1',
    184: 'MonTeleport',
    185: 'PrimeLightning',
    186: 'PrimeBolt',
    187: 'PrimeBlaze',
    188: 'PrimeFirewall',
    189: 'PrimeSpike',
    190: 'PrimeIceNova',
    191: 'PrimePoisonball',
    192: 'PrimePoisonNova',
    193: 'DiabLight',
    194: 'DiabCold',
    195: 'DiabFire',
    196: 'FingerMageSpider',
    197: 'DiabWall',
    198: 'DiabRun',
    199: 'DiabPrison',
    200: 'PoisonBallTrap',
    201: 'AndyPoisonBolt',
    202: 'HireableMissile',
    203: 'DesertTurret',
    204: 'ArcaneTower',
    205: 'MonBlizzard',
    206: 'Mosquito',
    207: 'CursedBallTrapRight',
    208: 'CursedBallTrapLeft',
    209: 'MonFrozenArmor',
    210: 'MonBoneArmor',
    211: 'MonBoneSpirit',
    212: 'MonCurseCast',
    213: 'HellMeteor',
    214: 'RegurgitatorEat',
    215: 'MonFrenzy',
    216: 'QueenDeath',
    217: 'Scroll of Identify',
    218: 'Book of Identify',
    219: 'Scroll of Townportal',
    220: 'Book of Townportal',
    221: 'Raven',
    222: 'Plague Poppy',
    223: 'Wearwolf',
    224: 'Shape Shifting',
    225: 'Firestorm',
    226: 'Oak Sage',
    227: 'Summon Spirit Wolf',
    228: 'Wearbear',
    229: 'Molten Boulder',
    230: 'Arctic Blast',
    231: 'Cycle of Life',
    232: 'Feral Rage',
    233: 'Maul',
    234: 'Eruption',
    235: 'Cyclone Armor',
    236: 'Heart of Wolverine',
    237: 'Summon Fenris',
    238: 'Rabies',
    239: 'Fire Claws',
    240: 'Twister',
    241: 'Vines',
    242: 'Hunger',
    243: 'Shock Wave',
    244: 'Volcano',
    245: 'Tornado',
    246: 'Spirit of Barbs',
    247: 'Summon Grizzly',
    248: 'Fury',
    249: 'Armageddon',
    250: 'Hurricane',
    251: 'Fire Trauma',
    252: 'Claw Mastery',
    253: 'Psychic Hammer',
    254: 'Tiger Strike',
    255: 'Dragon Talon',
    256: 'Shock Field',
    257: 'Blade Sentinel',
    258: 'Quickness',
    259: 'Fists of Fire',
    260: 'Dragon Claw',
    261: 'Charged Bolt Sentry',
    262: 'Wake of Fire Sentry',
    263: 'Weapon Block',
    264: 'Cloak of Shadows',
    265: 'Cobra Strike',
    266: 'Blade Fury',
    267: 'Fade',
    268: 'Shadow Warrior',
    269: 'Claws of Thunder',
    270: 'Dragon Tail',
    271: 'Lightning Sentry',
    272: 'Inferno Sentry',
    273: 'Mind Blast',
    274: 'Blades of Ice',
    275: 'Dragon Flight',
    276: 'Death Sentry',
    277: 'Blade Shield',
    278: 'Venom',
    279: 'Shadow Master',
    280: 'Royal Strike',
    281: 'Wake Of Destruction Sentry',
    282: 'Imp Inferno',
    283: 'Imp Fireball',
    284: 'Baal Taunt',
    285: 'Baal Corpse Explode',
    286: 'Baal Monster Spawn',
    287: 'Catapult Charged Ball',
    288: 'Catapult Spike Ball',
    289: 'Suck Blood',
    290: 'Cry Help',
    291: 'Healing Vortex',
    292: 'Teleport 2',
    293: 'Self-resurrect',
    294: 'Vine Attack',
    295: 'Overseer Whip',
    296: 'Barbs Aura',
    297: 'Wolverine Aura',
    298: 'Oak Sage Aura',
    299: 'Imp Fire Missile',
    300: 'Impregnate',
    301: 'Siege Beast Stomp',
    302: 'MinionSpawner',
    303: 'CatapultBlizzard',
    304: 'CatapultPlague',
    305: 'CatapultMeteor',
    306: 'BoltSentry',
    307: 'CorpseCycler',
    308: 'DeathMaul',
    309: 'Defense Curse',
    310: 'Blood Mana',
    311: 'mon inferno sentry',
    312: 'mon death sentry',
    313: 'sentry lightning',
    314: 'fenris rage',
    315: 'Baal Tentacle',
    316: 'Baal Nova',
    317: 'Baal Inferno',
    318: 'Baal Cold Missiles',
    319: 'MegademonInferno',
    320: 'EvilHutSpawner',
    321: 'CountessFirewall',
    322: 'ImpBolt',
    323: 'Horror Arctic Blast',
    324: 'death sentry ltng',
    325: 'VineCycler',
    326: 'BearSmite',
    327: 'Resurrect2',
    328: 'BloodLordFrenzy',
    329: 'Baal Teleport',
    330: 'Imp Teleport',
    331: 'Baal Clone Teleport',
    332: 'ZakarumLightning',
    333: 'VampireMissile',
    334: 'MephistoMissile',
    335: 'DoomKnightMissile',
    336: 'RogueMissile',
    337: 'HydraMissile',
    338: 'NecromageMissile',
    339: 'MonBow',
    340: 'MonFireArrow',
    341: 'MonColdArrow',
    342: 'MonExplodingArrow',
    343: 'MonFreezingArrow',
    344: 'MonPowerStrike',
    345: 'SuccubusBolt',
    346: 'MephFrostNova',
    347: 'MonIceSpear',
    348: 'ShamanIce',
    349: 'Diablogeddon',
    350: 'Delerium Change',
    351: 'NihlathakCorpseExplosion',
    352: 'SerpentCharge',
    353: 'Trap Nova',
    354: 'UnHolyBoltEx',
    355: 'ShamanFireEx',
    356: 'Imp Fire Missile Ex'
}

STATMAP = {
    0: 'Strength',                  	  # str
    1: 'Energy',                          # energy
    2: 'Dexterity',                       # dexterity
    3: 'Vitality',                        # vitality
    4: 'StatPointsLeft',
    5: 'NewSkills',
    6: 'Life',                              # life
    7: 'MaxLife',                           # max life
    8: 'Mana',                            # mana
    9: 'MaxMana',                         # max mana
    10: 'Stamina',                        # stamina
    11: 'MaxStamina',                     # max stamina
    12: 'Level',                          # level
    13: 'Exp',                            # experience
    14: 'Gold',                           # gold
    15: 'GoldBank',                       # stash gold
    16: 'EnhancedDefense',
    17: 'EnhancedMaximumDamage',
    18: 'EnhancedMinimumDamage',
    19: 'AttackRating',
    20: 'ToBlock',                        # to block
    21: 'MinimumDamage',
    22: 'MaximumDamage',
    23: 'SecondaryMinimumDamage',
    24: 'SecondaryMaximumDamage',
    25: 'EnhancedDamage',
    26: 'ManaRecovery',
    27: 'ManaRecoveryBonus',
    28: 'StaminaRecoveryBonus',
    29: 'LastExperience',
    30: 'NextExperience',
    31: 'Defense',
    32: 'DefenseVsMissiles',
    33: 'DefenseVsMelee',
    34: 'DmgReduction',
    35: 'MagicDmgReduction',              # magic damage reduction
    36: 'DmgReductionPct',                # damage reduction
    37: 'MagicDmgReductionPct',           # magic damage reduction percentage
    38: 'MaxMagicDmgReductPct',           # max magic damage reduction percentage
    39: 'FireResist',                     # fire resist
    40: 'MaxRireResist',                  # max fire resist
    41: 'LightningResist',                # lightning resist
    42: 'MaxLightningResist',             # max lightning resist
    43: 'ColdResist',                     # cold resist
    44: 'MaxColdResist',                  # max cold resist
    45: 'PoisonResist',                   # poison resist
    46: 'MaxPoisonResist',                # max poison resist
    47: 'DamagAaura',
    48: 'MinimumFireDamage',
    49: 'MaximumFireDamage',
    50: 'MinimumLightningDamage',
    51: 'MaximumLightningDamage',
    52: 'MinimumMagicalDamage',
    53: 'MaximumMagicalDamage',
    54: 'MinimumColdDamage',
    55: 'MaximumColdDamage',
    56: 'ColdDamageLength',
    57: 'MinimumPoisonDamage',
    58: 'MaximumPoisonDamage',
    59: 'PoisonDamageLength',
    60: 'LifeLeech',                      # Life Leech (min life stolen per hit)
    61: 'MaxLifeStolenPerHit',
    62: 'ManaLeech',                      # Mana Leech (min mana stolen per hit)
    63: 'MaxManaStolenPerHit',
    64: 'MinimumStaminaDrain',
    65: 'MaximumStaminaDrain',
    66: 'StunLength',
    67: 'VelocityPercent',                # effective run/walk
    68: 'AttackRate',
    69: 'OtherAnimationRate',
    70: 'AmmoQuantity',                   # ammo quantity(arrow/bolt/throwing)
    71: 'Value',
    72: 'Durability',                     # item durability
    73: 'MaxDurability',                  # max item durability
    74: 'ReplenishLife',
    75: 'EnhancedMaxDurability',
    76: 'EnhancedLife',
    77: 'EnhancedMana',
    78: 'AttackerTakesDamage',
    79: 'GoldFind',                       # Gold find (GF)
    80: 'MagicFind',                      # magic find (MF)
    81: 'Knockback',
    82: 'TimeDuration',
    83: 'ClassSkills',
    84: 'UnsentParameter',
    85: 'AddExperience',
    86: 'LifeAfterEachKill',
    87: 'ReduceVendorPrices',
    88: 'DoubleHerbDuration',
    89: 'LightRadius',
    90: 'LightColour',
    91: 'ReducedRequirements',
    92: 'ReducedLevelReq',
    93: 'IAS',                            # IAS
    94: 'ReducedLevelReqPct',
    95: 'LastBlockFrame',
    96: 'FasterRunWalk',                  # faster run/walk
    97: 'NonClassSkill',
    98: 'State',
    99: 'FasterHitRecovery',              # faster hit recovery
    100: 'MonsterPlayerCount',
    101: 'SkillPoisonOverrideLen',
    102: 'FasterBlock',                   # faster block rate
    103: 'SkillBypassUndead',
    104: 'SkillBypassDemons',
    105: 'FasterCast',                    # faster cast rate
    106: 'SkillBypassBeasts',
    107: 'SingleSkill',
    108: 'SlainMonstersRip',
    109: 'CurseResistance',
    110: 'PoisonLengthReduction',         # Poison length reduction
    111: 'AddsDamage',
    112: 'HitCausesMonsterToFlee',
    113: 'HitBlindsTarget',
    114: 'DamageToMana',
    115: 'IgnoreTargetsDefense',
    116: 'ReduceTargetsDefense',
    117: 'PreventMonsterHeal',
    118: 'HalfFreezeDuration',
    119: 'ToHitPercent',
    120: 'MonsterDefDuctPerHit',
    121: 'DamageToDemons',
    122: 'DamageToUndead',
    123: 'AttackRatingVsDemons',
    124: 'AttackRatingVsUndead',
    125: 'Throwable',
    126: 'ElementalSkills',
    127: 'AllSkills',
    128: 'AttackerTakesLtngDmg',
    129: 'IronMaidenLevel',
    130: 'LifetapLevel',
    131: 'ThornsPercent',
    132: 'BoneArmor',
    133: 'MaximumBoneArmor',
    134: 'FreezesTarget',
    135: 'OpenWounds',                    # Open Wounds
    136: 'CrushingBlow',                  # crushing blow
    137: 'KickDamage',
    138: 'ManaAfterEachKill',
    139: 'LifeAfterEachDemonKill',
    140: 'ExtraBlood',
    141: 'DeadlyStrike',                  # deadly strike
    142: 'FireAbsorbPercent',             # fire absorb %
    143: 'FireAbsorb',                    # fire absorb
    144: 'LightningAbsorbPercent',        # lightning absorb %
    145: 'LightningAbsorb',               # lightning absorb
    146: 'MagicAbsorbPercent',            # magic absorb %
    147: 'MagicAbsorb',
    148: 'ColdAbsorbPercent',             # cold absorb %
    149: 'ColdAbsorb',                    # cold absorb
    150: 'Slow',                          # slow %
    151: 'Aura',
    152: 'Indestructible',
    153: 'CannotBeFrozen',
    154: 'StaminaDrainPercent',
    155: 'Reanimate',
    156: 'PiercingAttack',
    157: 'FiresMagicArrows',
    158: 'FireExplosiveArrows',
    159: 'MinimumThrowingDamage',
    160: 'MaximumThrowingDamage',
    161: 'SkillHandOfAthena',
    162: 'SkillStaminaPercent',
    163: 'SkillPassiveStaminaPct',
    164: 'Concentration',
    165: 'Enchant',
    166: 'Pierce',
    167: 'Conviction',
    168: 'Chillingarmor',
    169: 'Frenzy',
    170: 'Decrepify',
    171: 'SkillArmorPercent',
    172: 'Alignment',
    173: 'Target0',
    174: 'Target1',
    175: 'GoldLost',
    176: 'ConversionLevel',
    177: 'ConversionMaximumLife',
    178: 'UnitDoOverlay',
    179: 'AttckRtngVsMonsterType',
    180: 'DamageToMonsterType',
    181: 'Fade',
    182: 'ArmorOverridePercent',
    183: 'Unused183',
    184: 'Unused184',
    185: 'Unused185',
    186: 'Unused186',
    187: 'Unused187',
    188: 'SkillTab',
    189: 'Unused189',
    190: 'Unused190',
    191: 'Unused191',
    192: 'Unused192',
    193: 'Unused193',
    194: 'Sockets',
    195: 'SkillOnStriking',
    196: 'SkillOnKill',
    197: 'SkillOnDeath',
    198: 'SkillOnHit',
    199: 'SkillOnLevelUp',
    200: 'Unused200',
    201: 'SkillWhenStruck',
    202: 'Unused202',
    203: 'Unused203',
    204: 'Charged',
    205: 'Unused204',
    206: 'Unused205',
    207: 'Unused206',
    208: 'Unused207',
    209: 'Unused208',
    210: 'Unused209',
    211: 'Unused210',
    212: 'Unused211',
    213: 'Unused212',
    214: 'DefensePerLevel',
    215: 'EnhancedDefensePerLvl',
    216: 'LifePerLevel',
    217: 'ManaPerLevel',
    218: 'MaxDamagePerLevel',
    219: 'MaxEnhancedDmgPerLevel',
    220: 'StrengthPerLevel',
    221: 'DexterityPerLevel',
    222: 'EnergyPerLevel',
    223: 'VitalityPerLevel',
    224: 'AttackRatingPerLevel',
    225: 'BonusAttckRtngPerLevel',
    226: 'MaxColdDmgPerLvl',
    227: 'MaxFireDmgPerLvl',
    228: 'MaxLightningDmgPerLvl',
    229: 'MaxPoisonDmgPerLvl',
    230: 'ColdResPerLevel',
    231: 'FireResPerLevel',
    232: 'LightningResPerLevel',
    233: 'PoisonResPerLevel',
    234: 'ColdAbsorbPerLvl',
    235: 'FireAbsorbPerLvl',
    236: 'LightningAbsorbPerLvl',
    237: 'PoisonAbsorbPerLvl',
    238: 'ThornsPerLevel',
    239: 'ExtraGoldPerLevel',
    240: 'MagicFindPerLevel',
    241: 'StaminaRegenPerLevel',
    242: 'StaminaPerLevel',
    243: 'DamageToDemonsPerLevel',
    244: 'DamageToUndeadPerLevel',
    245: 'AttkRtngVsDemonsPerLvl',
    246: 'AttkRtngVsUndeadPerLvl',
    247: 'CrushingBlowPerLevel',
    248: 'OpenWoundsPerLevel',
    249: 'KickDamagePerLevel',
    250: 'DeadlyStrikePerLevel',
    251: 'FindGemsPerLevel',
    252: 'RepairsDurability',
    253: 'ReplenishesQuantity',
    254: 'IncreasedStackSize',
    255: 'FindItem',
    256: 'SlashDamage',
    257: 'SlashDamagePercent',
    258: 'CrushDamage',
    259: 'CrushDamagePercent',
    260: 'ThrustDamage',
    261: 'ThrustDamagePercent',
    262: 'SlashDamageAbsorption',
    263: 'CrushDamageAbsorption',
    264: 'ThrustDamageAbsorption',
    265: 'SlashDamageAbsorbPct',
    266: 'CrushDamageAbsorbPct',
    267: 'ThrustDamageAbsorbPct',
    268: 'DefensePerTime',
    269: 'EnhancedDefensePerTime',
    270: 'LifePerTime',
    271: 'ManaPerTime',
    272: 'MaxDamagePerTime',
    273: 'MaxenhanceddmgPerTime',
    274: 'StrengthPerTime',
    275: 'DexterityPerTime',
    276: 'EnergyPerTime',
    277: 'VitalityPerTime',
    278: 'AttackRatingPerTime',
    279: 'ChanceToHitPerTime',
    280: 'MaxColdDamagePerTime',
    281: 'MaxFireDamagePerTime',
    282: 'MaxLightningDmgPerTime',
    283: 'MaxDamagePerPoison',
    284: 'ColdResPerTime',
    285: 'FireResPerTime',
    286: 'LightningResPerTime',
    287: 'PoisonResPerTime',
    288: 'ColdAbsorptionPerTime',
    289: 'FireAbsorptionPerTime',
    290: 'LightningAbsorbPerTime',
    291: 'PoisonAbsorbPerTime',
    292: 'ExtraGoldPerTime',
    293: 'MagicFindPerTime',
    294: 'RegenStaminaPerTime',
    295: 'StaminaPerTime',
    296: 'DamageToDemonsPerTime',
    297: 'DamageToUndeadPerTime',
    298: 'AttrtngVsDemonsPerTime',
    299: 'AttrtngVsUndeadPerTime',
    300: 'CrushingBlowPerTime',
    301: 'OpenWoundsPerTime',
    302: 'KickDamagePerTime',
    303: 'DeadlyStrikePerTime',
    304: 'FindGemsPerTime',
    305: 'EnemyColdresReduction',
    306: 'EnemyFireresReduction',
    307: 'EnemyLightresReduction',
    308: 'EnemyPsnResReduction',
    309: 'DamageVsMonsters',
    310: 'EnhancedDmgVsMonsters',
    311: 'AttackRatingVsMonsters',
    312: 'BonusAttRtngVsMonsters',
    313: 'DefenseVsMonsters',
    314: 'EnhancedDefVsMonsters',
    315: 'FireDamageLength',
    316: 'MinFireDamageLength',
    317: 'MaxFireDamageLength',
    318: 'ProgressiveDamage',
    319: 'ProgressiveSteal',
    320: 'ProgressiveOther',
    321: 'ProgressiveFire',
    322: 'ProgressiveCold',
    323: 'ProgressiveLightning',
    324: 'ExtraCharges',
    325: 'ProgressiveAttackRtng',
    326: 'PoisonCount',
    327: 'DamageFrameRate',
    328: 'PierceIdx',
    329: 'FireMastery',
    330: 'LightningMastery',
    331: 'ColdMastery',
    332: 'PoisonMastery',
    333: 'PsEnemyFireResReduc',           # passive enemy fire resist reduction
    334: 'PsEnemyLightnResReduc',         # passive enemy lightning resist reduction
    335: 'PsEnemyColdResReduc',           # passive enemy cold resist reduction
    336: 'PsEnemyPsnResReduc',            # passive enemy poison resist reduction
    337: 'CriticalStrike',
    338: 'Dodge',
    339: 'Avoid',
    340: 'Evade',
    341: 'Warmth',
    342: 'MeleeArMastery',                # melee attack rating mastery
    343: 'MeleeDamageMastery',
    344: 'MeleeCritHitMastery',
    345: 'ThrownWeaponArMastery',         # thrown weapon attack rating mastery
    346: 'ThrownWeaponDmgMastery',
    347: 'ThrownCritHitMastery',          # thrown weapon critical hit mastery
    348: 'WeaponBlock',
    349: 'SummonResist',
    350: 'ModifierListSkill',
    351: 'ModifierListLevel',
    352: 'LastSentLifePercent',
    353: 'SourceUnitType',
    354: 'SourceUnitId',
    355: 'ShortParameter1',
    356: 'QuestItemDifficulty',
    357: 'PassiveMagicDmgMastery',
    358: 'PassiveMagicResReduc'
}