FULL_ITEM_LIST = [
    "Aldur's Advance", "Aldur's Deception", "Aldur's Rhythm", "Aldur's Stony Gaze", "Alma Negra",
    "Amn Rune", "Andariel's Visage", "Angelic Halo", "Angelic Mantle", "Angelic Sickle",
    "Angelic Wings", "Annihilus", "Arachnid Mesh", "Arcanna's Deathwand", "Arcanna's Flesh",
    "Arcanna's Head", "Arcanna's Sign", "Arctic Binding", "Arctic Furs", "Arctic Horn",
    "Arctic Mitts", "Arioc's Needle", "Arkaine's Valor", "Arm of King Leoric", "Arreat's Face",
    "Astreon's Iron Ward", "Athena's Wrath", "Atma's Scarab", "Atma's Wail", "Axe of Fechmar",
    "Azurewrath", "Baezil's Vortex", "Bane Ash", "Baranar's Star", "Bartuc's Cut-Throat",
    "Ber Rune", "Berserker's Hatchet", "Berserker's Hauberk", "Berserker's Headgear",
    "Biggin's Bonnet", "Bing Sz Wang", "Black Hades", "Blackbog's Sharp", "Blackhand Key",
    "Blackhorn's Face", "Blackleach Blade", "Blackoak Shield", "Blacktongue", "Blade of Ali Baba",
    "Bladebone", "Bladebuckle", "Blastbark", "Blinkbat's Form", "Blood Crescent",
    "Blood Raven's Charge", "Bloodfist", "Bloodletter", "Bloodmoon", "Bloodrise", "Bloodthief",
    "Bloodtree Stump", "Boneflame", "Boneflesh", "Bonehew", "Boneshade", "Boneslayer Blade",
    "Bonesnap", "Brainhew", "Bul-Kathos' Sacred Charge", "Bul-Kathos' Tribal Guardian",
    "Bul-Kathos' Wedding Band", "Buriza-Do Kyanon", "Butcher's Pupil", "Bverrit Keep",
    "Carin Shard", "Carrion Wind", "Cathan's Mesh", "Cathan's Rule", "Cathan's Seal",
    "Cathan's Sigil", "Cathan's Visage", "Cerebus' Bite", "Cham Rune", "Chance Guards",
    "Chromatic Ire", "Civerb's Cudgel", "Civerb's Icon", "Civerb's Ward", "Cleglaw's Claw",
    "Cleglaw's Pincers", "Cleglaw's Tooth", "Cliffkiller", "Cloudcrack", "Coif of Glory",
    "Coldkill", "Coldsteel Eye", "Corpsemourn", "Cow King's Hide", "Cow King's Hooves",
    "Cow King's Horns", "Crainte Vomir", "Cranebeak", "Credendum", "Crescent Moon", "Crow Caw",
    "Crown of Ages", "Crown of Thieves", "Crushflange", "Culwen's Point", "Dangoon's Teaching",
    "Dark Adherent", "Dark Clan Crusher", "Darkforce Spawn", "Darkglow", "Darksight Helm",
    "Death Cleaver", "Deathbit", "Death's Fathom", "Death's Guard", "Death's Hand", "Death's Touch",
    "Death's Web", "Deathspade", "Demon Limb", "Demon Machine", "Demonhorn's Edge", "Demon's Arch",
    "Dimoak's Hew", "Djinn Slayer", "Dol Rune", "Doombringer", "Doomslinger", "Dracul's Grasp",
    "Dragonscale", "Duriel's Shell", "Duskdeep", "Dwarf Star", "Eaglehorn", "Earth Shifter",
    "Earthshaker", "El Rune", "Eld Rune", "Endlesshail", "Eschuta's Temper", "Eth Rune",
    "Ethereal Edge", "Executioner's Justice", "Fal Rune", "Felloak", "Firelizard's Talons",
    "Flamebellow", "Fleshrender", "Fleshripper", "Frostburn", "Frostwind", "Gargoyle's Bite",
    "Gerke's Sanctuary", "Gheed's Fortune", "Ghostflame", "Ghoulhide", "Giant Skull", "Gimmershred",
    "Ginther's Rift", "Gleamscythe", "Gloom's Trap", "Goblin Toe", "Goldskin", "Goldstrike Arch",
    "Goldwrap", "Gore Rider", "Gorefoot", "Goreshovel", "Gravenspine", "Gravepalm", "Greyform",
    "Griffon's Eye", "Grim's Burning Dead", "Griswold's Edge", "Griswold's Heart",
    "Griswold's Honor", "Griswold's Redemption", "Griswold's Valor", "Guardian Angel",
    "Guardian Naga", "Guillaume's Face", "Gul Rune", "Gull", "Gut Siphon", "Haemosu's Adamant",
    "Halaberd's Reign", "Hand of Blessed Light", "Harlequin Crest", "Hawkmail",
    "Head Hunter's Glory", "Headstriker", "Heart Carver", "Heavenly Garb", "Heaven's Light",
    "Hel Rune", "Hellcast", "Hellclap", "Hellfire Torch", "Hellmouth", "Hellplague", "Hellrack",
    "Hellslayer", "Herald of Zakarum", "Hexfire", "Highlord's Wrath", "Homunculus", "Hone Sundan",
    "Horizon's Tornado", "Hotspur", "Howltusk", "Hsarus' Iron Fist", "Hsarus' Iron Heel",
    "Hsarus' Iron Stay", "Humongous", "Husoldal Evo", "Hwanin's Blessing", "Hwanin's Justice",
    "Hwanin's Refuge", "Hwanin's Splendor", "Iceblink", "Ichorsting", "Immortal King's Detail",
    "Immortal King's Forge", "Immortal King's Pillar", "Immortal King's Soul Cage",
    "Immortal King's Stone Crusher", "Immortal King's Will", "Infernal Cranium", "Infernal Sign",
    "Infernal Torch", "Infernostride", "Io Rune", "Iratha's Coil", "Iratha's Collar",
    "Iratha's Cord", "Iratha's Cuff", "Iron Pelt", "Ironstone", "Isenhart's Case",
    "Isenhart's Horns", "Isenhart's Lightbrand", "Isenhart's Parry", "Islestrike", "Ist Rune",
    "Ith Rune", "Jade Talon", "Jah Rune", "Jalal's Mane", "Kelpie Snare", "Kinemil's Awl",
    "Kira's Guardian", "Knell Striker", "Ko Rune", "Kuko Shakaku", "Lacerator", "Lance Guard",
    "Lance of Yaggai", "Langer Briser", "Lava Gout", "Laying of Hands", "Leadcrow", "Lem Rune",
    "Lenymo", "Leviathan", "Lidless Wall", "Lightsabre", "Lo Rune", "Lum Rune", "Lycander's Aim",
    "Lycander's Flank", "Maelstrom", "Magefist", "Magewrath", "Magnus' Skin", "Mal Rune",
    "Manald Heal", "Mang Song's Lesson", "Mara's Kaleidoscope", "Marrowwalk", "M'avina's Caster",
    "M'avina's Embrace", "M'avina's Icy Clutch", "M'avina's Tenet", "M'avina's True Sight",
    "Medusa's Gaze", "Messerschmidt's Reaver", "Metalgrid", "Milabrega's Diadem", "Milabrega's Orb",
    "Milabrega's Robe", "Milabrega's Rod", "Moonfall", "Moser's Blessed Circle", "Nagelring",
    "Naj's Circlet", "Naj's Light Plate", "Naj's Puzzler", "Natalya's Mark", "Natalya's Shadow",
    "Natalya's Soul", "Natalya's Totem", "Nature's Peace", "Nef Rune", "Nightsmoke",
    "Nightwing's Veil", "Nokozan Relic", "Nord's Tenderizer", "Nosferatu's Coil", "Ohm Rune",
    "Ondal's Almighty", "Ondal's Wisdom", "Orb of Corruption", "Ormus' Robes", "Ort Rune",
    "Peasant Crown", "Pelta Lunata", "Pierre Tombale Couant", "Plague Bearer", "Pluckeye",
    "Pompeii's Wrath", "Pul Rune", "Pus Spitter", "Que-Hegan's Wisdom", "Radament's Sphere",
    "Rainbow Facet (Cold Die)", "Rainbow Facet (Cold Level Up)", "Rainbow Facet (Fire Die)",
    "Rainbow Facet (Fire Level Up)", "Rainbow Facet (Light Die)", "Rainbow Facet (Light Level Up)",
    "Rainbow Facet (Poison Die)", "Rainbow Facet (Poison Level Up)", "Rakescar", "Ral Rune", "Rattlecage",
    "Raven Claw", "Raven Frost", "Ravenlore", "Razor's Edge", "Razorswitch", "Razortail", "Razortine",
    "Ribcracker", "Riphook", "Ripsaw", "Rite of Passage", "Rixot's Keen", "Rockfleece", "Rockstopper",
    "Rogue's Bow", "Rune Master", "Rusthandle", "Sander's Paragon", "Sander's Riprap",
    "Sander's Superstition", "Sander's Taboo", "Sandstorm Trek", "Saracen's Chance",
    "Sazabi's Cobalt Redeemer", "Sazabi's Ghost Liberator", "Sazabi's Mental Sheath", "Schaefer's Hammer",
    "Seraph's Hymn", "Serpent Lord", "Shadow Dancer", "Shadow Killer", "Shadowfang", "Shael Rune",
    "Shaftstop", "Sigon's Gage", "Sigon's Guard", "Sigon's Sabot", "Sigon's Shelter", "Sigon's Visor",
    "Sigon's Wrap", "Silks of the Victor", "Silkweave", "Skewer of Krintiz",
    "Skin of the Flayed One", "Skin of the Vipermagi", "Skull Collector", "Skull Splitter",
    "Skullder's Ire", "Skystrike", "Snakecord", "Snowclash", "Sol Rune", "Soul Drainer",
    "Soul Harvest", "Soulfeast Tine", "Soulflay", "Sparking Mail", "Spectral Shard", "Spellsteel",
    "Spike Thorn", "Spineripper", "Spire of Honor", "Spire of Lazarus", "Spirit Forge",
    "Spirit Keeper", "Spirit Ward", "Stealskull", "Steel Carapace", "Steel Pillar", "Steel Shade",
    "Steelclash", "Steeldriver", "Steelgoad", "Steelrend", "Stone Crusher", "Stone of Jordan",
    "Stoneraven", "Stormchaser", "Stormeye", "Stormguild", "Stormlash", "Stormrider",
    "Stormshield", "Stormspike", "Stormspire", "Stormstrike", "Stoutnail", "String of Ears",
    "Suicide Branch", "Sur Rune", "Sureshrill Frost", "Swordback Hold", "Swordguard",
    "Taebaek's Glory", "Tal Rasha's Adjudication", "Tal Rasha's Fine Spun Cloth",
    "Tal Rasha's Guardianship", "Tal Rasha's Horadric Crest", "Tal Rasha's Lidless Eye", "Tal Rune",
    "Tancred's Crowbill", "Tancred's Hobnails", "Tancred's Skull", "Tancred's Spine",
    "Tancred's Weird", "Tarnhelm", "Tearhaunch", "Telling of Beads", "Templar's Might",
    "The Atlantean", "The Battlebranch", "The Cat's Eye", "The Centurion", "The Chieftain",
    "The Cranium Basher", "The Diggler", "The Dragon Chang", "The Eye of Etlich",
    "The Face of Horror", "The Fetid Sprinkler", "The Gavel of Pain", "The General's Tan Do Li Ga",
    "The Gladiator's Bane", "The Gnasher", "The Grandfather", "The Grim Reaper",
    "The Hand of Broc", "The Impaler", "The Iron Jang Bong", "The Jade Tan Do",
    "The Mahim-Oak Curio", "The Meat Scraper", "The Minotaur", "The Oculus", "The Patriarch",
    "The Reaper's Toll", "The Redeemer", "The Rising Sun", "The Salamander", "The Scalper",
    "The Spirit Shroud", "The Tannr Gorerod", "The Vile Husk", "The Ward", "Thul Rune",
    "Thundergod's Vigor", "Thunderstroke", "Tiamat's Rebuke", "Tir Rune", "Titan's Revenge",
    "Todesfaelle Flamme", "Tomb Reaver", "Toothrow", "Torch of Iro", "Trang-Oul's Claws",
    "Trang-Oul's Girth", "Trang-Oul's Guise", "Trang-Oul's Scales", "Trang-Oul's Wing",
    "Treads of Cthon", "Twitchthroe", "Tyrael's Might", "Um Rune", "Umbral Disk",
    "Ume's Lament", "Undead Crown", "Valkyrie Wing", "Vampire Gaze", "Veil of Steel",
    "Venom Grip", "Venom Ward", "Verdungo's Hearty Cord", "Vex Rune", "Vidala's Ambush",
    "Vidala's Barb", "Vidala's Fetlock", "Vidala's Snare", "Viperfork", "Visceratuant",
    "Wall of the Eyeless", "War Traveler", "Warlord's Trust", "Warpspear", "Warshrike", "Waterwalk",
    "Whitstan's Guard", "Widowmaker", "Wilhelm's Pride", "Windforce", "Windhammer",
    "Wisp Projector", "Witchwild String", "Witherstring", "Wizardspike", "Wizendraw", "Woestave",
    "Wolfhowl", "Wormskull", "Wraith Flight", "Zakarum's Hand", "Zod Rune",
    "Key of Destruction", "Key of Hate", "Key of Terror"

    "Aegis (Unique)", "Amulet (Set)", "Amulet (Unique)", "Ancient Armor (Set)", "Ancient Armor (Unique)",
    "Ancient Axe (Unique)", "Ancient Shield (Unique)", "Ancient Sword (Unique)", "Arbalest (Unique)",
    "Archon Staff (Unique)", "Armet (Unique)", "Ataghan (Unique)", "Avenger Guard (Set)", "Axe (Unique)",
    "Ballista (Unique)", "Balrog Blade (Unique)", "Balrog Skin (Set)", "Balrog Skin (Unique)", "Balrog Spear (Unique)",
    "Barbed Club (Unique)", "Barbed Shield (Unique)", "Bardiche (Unique)", "Basinet (Set)", "Basinet (Unique)",
    "Bastard Sword (Unique)", "Battle Axe (Unique)", "Battle Belt (Set)", "Battle Belt (Unique)", "Battle Boots (Set)",
    "Battle Boots (Unique)", "Battle Cestus (Unique)", "Battle Dart (Unique)", "Battle Gauntlets (Set)",
    "Battle Gauntlets (Unique)", "Battle Hammer (Unique)", "Battle Scythe (Unique)", "Battle Staff (Set)",
    "Battle Staff (Unique)", "Battle Sword (Unique)", "Bearded Axe (Unique)", "Bec-De-Corbin (Unique)", "Belt (Set)",
    "Belt (Unique)", "Berserker Axe (Unique)", "Bill (Set)", "Bill (Unique)", "Blade (Unique)",
    "Blade Barrier (Unique)", "Blood Spirit (Unique)", "Bloodlord Skull (Unique)", "Bone Helm (Set)",
    "Bone Helm (Unique)", "Bone Knife (Unique)", "Bone Shield (Unique)", "Bone Visage (Set)", "Bone Visage (Unique)",
    "Bone Wand (Set)", "Bone Wand (Unique)", "Boneweave Boots (Unique)", "Boots (Set)", "Boots (Unique)",
    "Bramble Mitts (Set)", "Brandistock (Unique)", "Breast Plate (Set)", "Breast Plate (Unique)", "Broad Axe (Unique)",
    "Broad Sword (Set)", "Broad Sword (Unique)", "Buckler (Set)", "Buckler (Unique)", "Burnt Wand (Unique)",
    "Caduceus (Set)", "Caduceus (Unique)", "Cantor Trophy (Set)", "Cap (Set)", "Cap (Unique)", "Casque (Unique)",
    "Cedar Bow (Unique)", "Cedar Staff (Unique)", "Ceremonial Bow (Unique)", "Ceremonial Javelin (Unique)",
    "Ceremonial Pike (Unique)", "Chain Boots (Set)", "Chain Boots (Unique)", "Chain Gloves (Set)",
    "Chain Gloves (Unique)", "Chain Mail (Set)", "Chain Mail (Unique)", "Champion Axe (Unique)",
    "Champion Sword (Unique)", "Chaos Armor (Set)", "Chaos Armor (Unique)", "Chu-Ko-Nu (Unique)", "Cinquedeas (Unique)",
    "Circlet (Set)", "Claymore (Unique)", "Cleaver (Unique)", "Club (Unique)", "Colossus Blade (Set)",
    "Colossus Blade (Unique)", "Colossus Crossbow (Unique)", "Composite Bow (Unique)", "Conqueror Crown (Unique)",
    "Corona (Set)", "Corona (Unique)", "Crossbow (Unique)", "Crowbill (Unique)", "Crown (Set)", "Crown (Unique)",
    "Crusader Bow (Unique)", "Cryptic Axe (Unique)", "Cryptic Sword (Set)", "Cryptic Sword (Unique)", "Cudgel (Unique)",
    "Cuirass (Set)", "Cuirass (Unique)", "Cutlass (Unique)", "Dacian Falx (Unique)", "Dagger (Unique)",
    "Death Mask (Set)", "Death Mask (Unique)", "Decapitator (Unique)", "Defender (Unique)", "Demon Crossbow (Unique)",
    "Demonhead (Unique)", "Demonhide Armor (Unique)", "Demonhide Boots (Set)", "Demonhide Boots (Unique)",
    "Demonhide Gloves (Unique)", "Demonhide Sash (Unique)", "Destroyer Helm (Unique)", "Devil Star (Unique)",
    "Diadem (Set)", "Diadem (Unique)", "Dimensional Blade (Unique)", "Dimensional Shard (Unique)", "Dirk (Unique)",
    "Divine Scepter (Unique)", "Double Axe (Set)", "Double Axe (Unique)", "Double Bow (Unique)",
    "Dragon Shield (Unique)", "Dusk Shroud (Set)", "Dusk Shroud (Unique)", "Earth Spirit (Unique)", "Edge Bow (Unique)",
    "Elder Staff (Set)", "Elder Staff (Unique)", "Eldritch Orb (Unique)", "Elegant Blade (Unique)",
    "Embossed Plate (Unique)", "Espandon (Unique)", "Ettin Axe (Unique)", "Executioner Sword (Unique)",
    "Falchion (Unique)", "Fanged Knife (Unique)", "Feral Claws (Unique)", "Field Plate (Unique)", "Flail (Unique)",
    "Flamberge (Unique)", "Flanged Mace (Unique)", "Flying Axe (Unique)", "Francisca (Unique)", "Full Helm (Set)",
    "Full Helm (Unique)", "Full Plate Mail (Set)", "Full Plate Mail (Unique)", "Fury Visor (Unique)",
    "Fuscina (Unique)", "Gauntlets (Set)", "Gauntlets (Unique)", "Ghost Armor (Unique)", "Ghost Glaive (Unique)",
    "Giant Axe (Unique)", "Giant Sword (Unique)", "Giant Thresher (Unique)", "Gilded Shield (Unique)",
    "Gladius (Unique)", "Glorious Axe (Unique)", "Gnarled Staff (Unique)", "Gothic Axe (Unique)", "Gothic Bow (Unique)",
    "Gothic Plate (Set)", "Gothic Plate (Unique)", "Gothic Shield (Set)", "Gothic Shield (Unique)",
    "Gothic Staff (Unique)", "Gothic Sword (Unique)", "Grand Charm (Unique)", "Grand Crown (Set)",
    "Grand Crown (Unique)", "Grand Matron Bow (Set)", "Grand Scepter (Set)", "Grand Scepter (Unique)",
    "Grave Wand (Unique)", "Great Axe (Unique)", "Great Helm (Set)", "Great Helm (Unique)", "Great Maul (Unique)",
    "Great Sword (Unique)", "Greater Talons (Unique)", "Greaves (Set)", "Greaves (Unique)", "Grim Helm (Set)",
    "Grim Helm (Unique)", "Grim Scythe (Unique)", "Grim Shield (Unique)", "Grim Wand (Set)", "Grim Wand (Unique)",
    "Halberd (Unique)", "Hand Axe (Unique)", "Hard Leather Armor (Unique)", "Hatchet (Unique)", "Heavy Belt (Set)",
    "Heavy Belt (Unique)", "Heavy Boots (Set)", "Heavy Boots (Unique)", "Heavy Bracers (Set)", "Heavy Bracers (Unique)",
    "Heavy Crossbow (Unique)", "Heavy Gloves (Set)", "Heavy Gloves (Unique)", "Hellforge Plate (Set)", "Helm (Set)",
    "Helm (Unique)", "Hierophant Trophy (Unique)", "Holy Water Sprinkler (Unique)", "Hunter's Bow (Unique)",
    "Hunter's Guise (Set)", "Hydra Bow (Unique)", "Hyperion Spear (Unique)", "Jagged Star (Set)",
    "Jagged Star (Unique)", "Jewel (Unique)", "Jo Staff (Unique)", "Kite Shield (Set)", "Kite Shield (Unique)",
    "Knout (Unique)", "Kraken Shell (Set)", "Kraken Shell (Unique)", "Kris (Unique)", "Lacquered Plate (Set)",
    "Lance (Unique)", "Large Axe (Unique)", "Large Charm (Unique)", "Large Shield (Set)", "Large Shield (Unique)",
    "Large Siege Bow (Unique)", "Leather Armor (Set)", "Leather Armor (Unique)", "Leather Gloves (Set)",
    "Leather Gloves (Unique)", "Legend Spike (Unique)", "Legendary Mallet (Unique)", "Lich Wand (Unique)",
    "Light Belt (Set)", "Light Belt (Unique)", "Light Crossbow (Unique)", "Light Gauntlets (Set)",
    "Light Gauntlets (Unique)", "Light Plate (Set)", "Light Plate (Unique)", "Light Plated Boots (Set)",
    "Light Plated Boots (Unique)", "Linked Mail (Unique)", "Lochaber Axe (Unique)", "Long Battle Bow (Set)",
    "Long Battle Bow (Unique)", "Long Bow (Unique)", "Long Staff (Unique)", "Long Sword (Set)", "Long Sword (Unique)",
    "Long War Bow (Unique)", "Loricated Mail (Set)", "Luna (Unique)", "Mace (Unique)", "Mage Plate (Unique)",
    "Mancatcher (Unique)", "Martel de Fer (Unique)", "Mask (Set)", "Mask (Unique)", "Matriarcal Spear (Unique)",
    "Matriarchal Bow (Unique)", "Matriarchal Javelin (Unique)", "Maul (Unique)", "Mesh Armor (Unique)",
    "Mesh Belt (Set)", "Mesh Belt (Unique)", "Mesh Boots (Set)", "Mesh Boots (Unique)", "Mighty Scepter (Unique)",
    "Military Axe (Unique)", "Military Pick (Set)", "Military Pick (Unique)", "Mithril Coil (Set)",
    "Mithril Coil (Unique)", "Monarch (Unique)", "Morning Star (Unique)", "Myrmidon Greaves (Unique)",
    "Mythical Sword (Set)", "Naga (Unique)", "Ogre Axe (Unique)", "Ogre Gauntlets (Unique)", "Ogre Maul (Set)",
    "Ogre Maul (Unique)", "Ornate Plate (Set)", "Ornate Plate (Unique)", "Partizan (Unique)", "Pavise (Unique)",
    "Petrified Wand (Unique)", "Phase Blade (Unique)", "Pike (Unique)", "Plate Mail (Unique)", "Plated Belt (Set)",
    "Plated Belt (Unique)", "Poignard (Unique)", "Poleaxe (Unique)", "Quarterstaff (Unique)", "Quilted Armor (Set)",
    "Quilted Armor (Unique)", "Razor Bow (Unique)", "Reinforced Mace (Set)", "Repeating Crossbow (Unique)",
    "Ring (Set)", "Ring (Unique)", "Ring Mail (Set)", "Ring Mail (Unique)", "Rondel (Unique)", "Round Shield (Set)",
    "Round Shield (Unique)", "Rune Bow (Unique)", "Rune Scepter (Unique)", "Rune Staff (Unique)", "Rune Sword (Unique)",
    "Russet Armor (Unique)", "Sabre (Set)", "Sabre (Unique)", "Sacred Armor (Set)", "Sacred Armor (Unique)",
    "Sacred Rondache (Unique)", "Sallet (Unique)", "Sash (Set)", "Sash (Unique)", "Scale Mail (Unique)",
    "Scarabshell Boots (Unique)", "Scepter (Unique)", "Scimitar (Unique)", "Scissors Suwayyah (Set)",
    "Scourge (Unique)", "Scutum (Unique)", "Scythe (Unique)", "Serpentskin Armor (Unique)", "Shadow Plate (Set)",
    "Shadow Plate (Unique)", "Shako (Unique)", "Shamshir (Unique)", "Sharkskin Armor (Unique)", "Sharkskin Belt (Set)",
    "Sharkskin Belt (Unique)", "Sharkskin Boots (Unique)", "Sharkskin Gloves (Set)", "Sharkskin Gloves (Unique)",
    "Short Battle Bow (Unique)", "Short Bow (Unique)", "Short Siege Bow (Unique)", "Short Staff (Unique)",
    "Short Sword (Unique)", "Short War Bow (Set)", "Short War Bow (Unique)", "Siege Crossbow (Unique)",
    "Silver-Edged Axe (Unique)", "Skull Cap (Set)", "Skull Cap (Unique)", "Sky Spirit (Unique)",
    "Slayer Guard (Unique)", "Small Charm (Unique)", "Small Shield (Set)", "Small Shield (Unique)",
    "Spear (Unique)", "Spetum (Unique)", "Spiderweb Sash (Unique)", "Spiked Club (Unique)", "Spiked Shield (Unique)",
    "Spired Helm (Set)", "Spired Helm (Unique)", "Splint Mail (Set)", "Splint Mail (Unique)", "Stiletto (Unique)",
    "Studded Leather (Set)", "Studded Leather (Unique)", "Succubus Skull (Unique)", "Swirling Crystal (Set)",
    "Swirling Crystal (Unique)", "Tabar (Unique)", "Templar Coat (Unique)", "Thresher (Unique)",
    "Thunder Maul (Unique)", "Tiara (Unique)", "Tigulated Mail (Set)", "Tigulated Mail (Unique)", "Tomahawk (Unique)",
    "Tomb Wand (Unique)", "Totemic Mask (Unique)", "Tower Shield (Set)", "Tower Shield (Unique)",
    "Trellised Armor (Unique)", "Trident (Unique)", "Troll Belt (Set)", "Troll Nest (Unique)", "Truncheon (Unique)",
    "Tulwar (Unique)", "Tusk Sword (Unique)", "Twin Axe (Unique)", "Two-Handed Sword (Unique)", "Tyrant Club (Unique)",
    "Unearthed Wand (Unique)", "Vambraces (Unique)", "Vampirebone Gloves (Unique)", "Vampirefang Belt (Unique)",
    "Vortex Shield (Set)", "Voulge (Unique)", "Wand (Unique)", "War Axe (Unique)", "War Belt (Set)",
    "War Belt (Unique)", "War Boots (Set)", "War Boots (Unique)", "War Club (Unique)", "War Fork (Unique)",
    "War Gauntlets (Set)", "War Gauntlets (Unique)", "War Hammer (Unique)", "War Hat (Set)", "War Hat (Unique)",
    "War Pike (Unique)", "War Scepter (Set)", "War Scepter (Unique)", "War Scythe (Unique)", "War Spear (Unique)",
    "War Spike (Unique)", "War Staff (Set)", "War Staff (Unique)", "War Sword (Set)", "War Sword (Unique)",
    "Ward (Set)", "Ward (Unique)", "Ward Bow (Unique)", "Winged Axe (Unique)", "Winged Harpoon (Unique)",
    "Winged Helm (Set)", "Winged Helm (Unique)", "Winged Knife (Unique)", "Wire Fleece (Unique)",
    "Wrist Sword (Unique)", "Yari (Unique)", "Yew Wand (Unique)", "Zakarum Shield (Unique)", "Zweihander (Unique)",

    "Grand Charm (Magic)", "Large Charm (Magic)", "Small Charm (Magic)", "Jewel (Magic)",
]



ITEM_ALIASES = {"Aldur's Boots": "Aldur's Advance",
                "Aldur's Weapon": "Aldur's Rhythm",
                "Aldur's Armor": "Aldur's Deception",
                "Aldur's Helm": "Aldur's Stony Gaze",
                "Andy's Face": "Andariel's Visage",
                'Angelic Amu': 'Angelic Wings',
                'Angelic Ring': 'Angelic Halo',
                'Angelic Armor': 'Angelic Mantle',
                'Angelic Weapon': 'Angelic Sickle',
                'BK ring': "Bul-Kathos' Wedding Band",
                'CoA': 'Crown of Ages',
                'DF': "Death's Fathom",
                'Dkey': 'Key of Destruction',
                'Dweb': "Death's Web",
                'G Angel': 'Guardian Angel',
                'GAngel': 'Guardian Angel',
                'GF': 'The Grandfather',
                "Griswold's Armor": "Griswold's Heart",
                "Griswold's Helm": "Griswold's Valor",
                "Griswold's Shield": "Griswold's Honor",
                "Griswold's Weapon": "Griswold's Redemption",
                "Griswold's Caduceus": "Griswold's Redemption",
                "Gris Caduceus": "Griswold's Redemption",
                "Gris Armor": "Griswold's Heart",
                "Gris Helm": "Griswold's Valor",
                "Gris Shield": "Griswold's Honor",
                "Gris Weapon": "Griswold's Redemption",
                'Gull Dagger': 'Gull',
                'HoZ': 'Herald of Zakarum',
                'Hkey': 'Key of Hate',
                'IK Armor': "Immortal King's Soul Cage",
                'IK Weapon': "Immortal King's Stone Crusher",
                'IK Helm': "Immortal King's Will",
                'IK Belt': "Immortal King's Detail",
                'IK Boots': "Immortal King's Pillar",
                'IK Gloves': "Immortal King's Forge",
                "Immortal King's Armor": "Immortal King's Soul Cage",
                "Immortal King's Weapon": "Immortal King's Stone Crusher",
                "Immortal King's Helm": "Immortal King's Will",
                "Immortal King's Belt": "Immortal King's Detail",
                "Immortal King's Boots": "Immortal King's Pillar",
                "Immortal King's Gloves": "Immortal King's Forge",
                'KoD': 'Key of Destruction',
                'KoH': 'Key of Hate',
                'KoT': 'Key of Terror',
                'LoH': 'Laying of Hands',
                "M'avina's Bow": "M'avina's Caster",
                "M'avina's Armor": "M'avina's Embrace",
                "M'avina's Gloves": "M'avina's Icy Clutch",
                "M'avina's Belt": "M'avina's Tenet",
                "M'avina's Diadem": "M'avina's True Sight",
                "M'avina's Helm": "M'avina's True Sight",
                'Mahim Oak': 'The Mahim-Oak Curio',
                'Nagel Ring': 'Nagelring',
                'OOC': 'Orb of Corruption',
                'Occu': 'The Oculus',
                'Occy': 'The Oculus',
                "Que Hegan's Wisdom": "Que-Hegan's Wisdom",
                'RBF cold die': 'Rainbow Facet (Cold Die)',
                'RBF cold level up': 'Rainbow Facet (Cold Level Up)',
                'RBF fire die': 'Rainbow Facet (Fire Die)',
                'RBF fire level up': 'Rainbow Facet (Fire Level Up)',
                'RBF light die': 'Rainbow Facet (Light Die)',
                'RBF light level up': 'Rainbow Facet (Light Level Up)',
                'RBF poison die': 'Rainbow Facet (Poison Die)',
                'RBF poison level up': 'Rainbow Facet (Poison Level Up)',
                'Rainbow Facet cold die': 'Rainbow Facet (Cold Die)',
                'Rainbow Facet cold level up': 'Rainbow Facet (Cold Level Up)',
                'Rainbow Facet fire die': 'Rainbow Facet (Fire Die)',
                'Rainbow Facet fire level up': 'Rainbow Facet (Fire Level Up)',
                'Rainbow Facet light die': 'Rainbow Facet (Light Die)',
                'Rainbow Facet light level up': 'Rainbow Facet (Light Level Up)',
                'Rainbow Facet poison die': 'Rainbow Facet (Poison Die)',
                'Rainbow Facet poison level up': 'Rainbow Facet (Poison Level Up)',
                'Shako': 'Harlequin Crest',
                'SoE': 'String of Ears',
                'SoJ': 'Stone of Jordan',
                'SS': 'Stormshield',
                "Sigon's Armor": "Sigon's Shelter",
                "Sigon's Belt": "Sigon's Wrap",
                "Sigon's Boots": "Sigon's Sabot",
                "Sigon's Gloves": "Sigon's Gage",
                "Sigon's Helm": "Sigon's Visor",
                "Sigon's Shield": "Sigon's Guard",
                'Tkey': 'Key of Terror',
                'TGS': "Thundergod's Vigor",
                'TGods': "Thundergod's Vigor",
                'Tal Amu': "Tal Rasha's Adjudication",
                'Tal Armor': "Tal Rasha's Guardianship",
                'Tal Belt': "Tal Rasha's Fine Spun Cloth",
                'Tal Helm': "Tal Rasha's Horadric Crest",
                'Tal Orb': "Tal Rasha's Lidless Eye",
                'Tal Weapon': "Tal Rasha's Lidless Eye",
                "Tancred's Amu": "Tancred's Weird",
                'Trang Armor': "Trang-Oul's Scales",
                'Trang Belt': "Trang-Oul's Girth",
                'Trang Gloves': "Trang-Oul's Claws",
                'Trang Helm': "Trang-Oul's Guise",
                'Trang Shield': "Trang-Oul's Wing",
                'Vgaze': 'Vampire Gaze',
                'WForce': 'Windforce',
                'WTrav': 'War Traveler',
                'WWs': 'Waterwalk',
                'Wizzy': 'Wizardspike'}